// Pulse808 Web Audio Beat Machine & Synthesizer Template
// 16-step sequencer, native Web Audio API synthesis (zero audio sample dependencies), BPM controls, and pattern presets

const html = `
<div class="synth-container">
  <!-- Top Chassis Header -->
  <header class="chassis-header">
    <div class="synth-brand">
      <div class="synth-badge">PULSE-808</div>
      <div>
        <div class="chassis-title">Rhythm Composer & Analog Bass Synth</div>
        <div class="chassis-sub">Native Web Audio API • 16-Step Dual Matrix</div>
      </div>
    </div>

    <!-- Transport Controls -->
    <div class="transport-controls">
      <button class="transport-btn play-btn" id="playToggleBtn">
        <svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor" id="playIcon">
          <polygon points="5 3 19 12 5 21 5 3"/>
        </svg>
        <span id="playText">PLAY</span>
      </button>

      <button class="transport-btn clear-btn" id="clearPatternBtn">CLEAR</button>

      <div class="bpm-control">
        <div class="bpm-header">
          <label>TEMPO (BPM)</label>
          <span class="bpm-val" id="bpmVal">128</span>
        </div>
        <input type="range" min="70" max="175" value="128" id="bpmSlider" class="synth-slider">
      </div>
    </div>

    <!-- Presets -->
    <div class="preset-group">
      <span class="preset-label">PRESET:</span>
      <button class="preset-btn active" data-preset="house">House</button>
      <button class="preset-btn" data-preset="trap">Trap</button>
      <button class="preset-btn" data-preset="electro">Electro</button>
    </div>
  </header>

  <!-- Step Sequencer Chassis -->
  <main class="chassis-body">
    <!-- Running Step Indicators (1-16) -->
    <div class="step-ruler">
      <div class="ruler-spacer"></div>
      <div class="ruler-leds" id="rulerLeds">
        <!-- 16 step LEDs generated by JS -->
      </div>
    </div>

    <!-- Channel Rows -->
    <div class="channel-matrix">
      <!-- Row 1: BD (Bass Drum / Kick) -->
      <div class="channel-row" data-channel="kick">
        <div class="channel-info">
          <button class="trigger-pad pad-kick" data-sound="kick">BD 808</button>
          <div class="channel-params">
            <span class="param-name">KICK</span>
            <span class="param-hz">55 Hz</span>
          </div>
        </div>
        <div class="steps-container" data-ch="0" id="steps-kick">
          <!-- 16 step buttons -->
        </div>
      </div>

      <!-- Row 2: SD (Snare Drum) -->
      <div class="channel-row" data-channel="snare">
        <div class="channel-info">
          <button class="trigger-pad pad-snare" data-sound="snare">SD 808</button>
          <div class="channel-params">
            <span class="param-name">SNARE</span>
            <span class="param-hz">Noise/Tone</span>
          </div>
        </div>
        <div class="steps-container" data-ch="1" id="steps-snare">
          <!-- 16 step buttons -->
        </div>
      </div>

      <!-- Row 3: CH (Closed Hi-Hat) -->
      <div class="channel-row" data-channel="hat">
        <div class="channel-info">
          <button class="trigger-pad pad-hat" data-sound="hat">CH 808</button>
          <div class="channel-params">
            <span class="param-name">HI-HAT</span>
            <span class="param-hz">Hi-Pass</span>
          </div>
        </div>
        <div class="steps-container" data-ch="2" id="steps-hat">
          <!-- 16 step buttons -->
        </div>
      </div>

      <!-- Row 4: BASS (Acid Synth Bass) -->
      <div class="channel-row" data-channel="bass">
        <div class="channel-info">
          <button class="trigger-pad pad-bass" data-sound="bass">SYNTH</button>
          <div class="channel-params">
            <span class="param-name">BASS 303</span>
            <span class="param-hz">Saw Wave</span>
          </div>
        </div>
        <div class="steps-container" data-ch="3" id="steps-bass">
          <!-- 16 step buttons -->
        </div>
      </div>
    </div>

    <!-- Analog Filter Strip -->
    <div class="fx-strip">
      <div class="fx-card">
        <div class="fx-title">MASTER RESO FILTER</div>
        <div class="fx-controls">
          <div class="dial-wrapper">
            <label>Cutoff (Hz)</label>
            <input type="range" min="200" max="6000" value="3500" id="filterCutoff" class="synth-slider">
            <span id="cutoffVal" class="dial-val">3500 Hz</span>
          </div>
          <div class="dial-wrapper">
            <label>Resonance (Q)</label>
            <input type="range" min="1" max="15" value="4" id="filterReso" class="synth-slider">
            <span id="resoVal" class="dial-val">4.0</span>
          </div>
        </div>
      </div>

      <div class="fx-card">
        <div class="fx-title">OUTPUT METERS</div>
        <div class="meter-bar-container">
          <div class="vu-meter">
            <div class="vu-bar" id="vuLeft" style="height: 10%;"></div>
          </div>
          <div class="vu-meter">
            <div class="vu-bar" id="vuRight" style="height: 10%;"></div>
          </div>
          <div class="meter-labels">
            <span>0 dB</span>
            <span>-6 dB</span>
            <span>-12 dB</span>
            <span>-24 dB</span>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>
`;

const css = `
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: 'SFMono-Regular', Consolas, Menlo, Monaco, monospace;
  background-color: #121214;
  color: #e4e4e7;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.synth-container {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  background: radial-gradient(circle at 50% 20%, #1e1e24, #0f0f12);
  padding: 24px;
}

.chassis-header {
  background: #18181b;
  border: 1px solid #27272a;
  border-radius: 12px 12px 0 0;
  padding: 18px 24px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 16px;
  box-shadow: 0 4px 14px rgba(0, 0, 0, 0.4);
}

.synth-brand {
  display: flex;
  align-items: center;
  gap: 14px;
}

.synth-badge {
  background: linear-gradient(135deg, #f97316, #ef4444);
  color: #ffffff;
  font-size: 14px;
  font-weight: 900;
  padding: 6px 12px;
  border-radius: 6px;
  letter-spacing: 0.1em;
  box-shadow: 0 0 12px rgba(249, 115, 22, 0.4);
}

.chassis-title {
  font-size: 15px;
  font-weight: 700;
  color: #fafafa;
}

.chassis-sub {
  font-size: 11px;
  color: #71717a;
}

.transport-controls {
  display: flex;
  align-items: center;
  gap: 16px;
}

.transport-btn {
  padding: 8px 18px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 800;
  font-family: inherit;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 8px;
  transition: all 0.15s ease;
  border: 1px solid transparent;
}

.play-btn {
  background: #10b981;
  color: #022c22;
  box-shadow: 0 0 14px rgba(16, 185, 129, 0.4);
}

.play-btn.playing {
  background: #ef4444;
  color: #ffffff;
  box-shadow: 0 0 14px rgba(239, 68, 68, 0.5);
}

.clear-btn {
  background: #27272a;
  color: #a1a1aa;
  border-color: #3f3f46;
}

.clear-btn:hover {
  background: #3f3f46;
  color: #ffffff;
}

.bpm-control {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.bpm-header {
  display: flex;
  justify-content: space-between;
  font-size: 10px;
  color: #71717a;
}

.bpm-val {
  color: #f97316;
  font-weight: bold;
}

.synth-slider {
  width: 110px;
  accent-color: #f97316;
  cursor: pointer;
}

.preset-group {
  display: flex;
  align-items: center;
  gap: 6px;
}

.preset-label {
  font-size: 10px;
  color: #71717a;
}

.preset-btn {
  background: #27272a;
  color: #a1a1aa;
  border: 1px solid #3f3f46;
  font-size: 11px;
  font-family: inherit;
  padding: 4px 10px;
  border-radius: 4px;
  cursor: pointer;
}

.preset-btn.active {
  background: #f97316;
  color: #000000;
  border-color: #ea580c;
  font-weight: bold;
}

/* Chassis Body */
.chassis-body {
  background: #18181b;
  border: 1px solid #27272a;
  border-top: none;
  border-radius: 0 0 12px 12px;
  padding: 24px;
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

/* Step Ruler */
.step-ruler {
  display: flex;
  align-items: center;
  gap: 16px;
}

.ruler-spacer {
  width: 140px;
  flex-shrink: 0;
}

.ruler-leds {
  flex: 1;
  display: grid;
  grid-template-columns: repeat(16, 1fr);
  gap: 6px;
}

.step-led {
  height: 8px;
  background: #27272a;
  border-radius: 2px;
  transition: background 0.05s ease;
}

.step-led.active {
  background: #f97316;
  box-shadow: 0 0 10px #f97316, 0 0 20px #f97316;
}

/* Channels */
.channel-matrix {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.channel-row {
  display: flex;
  align-items: center;
  gap: 16px;
}

.channel-info {
  width: 140px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  gap: 10px;
}

.trigger-pad {
  width: 54px;
  height: 44px;
  border-radius: 6px;
  border: none;
  font-family: inherit;
  font-size: 11px;
  font-weight: 800;
  cursor: pointer;
  transition: transform 0.05s, filter 0.1s;
}

.trigger-pad:active {
  transform: scale(0.94);
  filter: brightness(1.3);
}

.pad-kick { background: #dc2626; color: #fff; }
.pad-snare { background: #ea580c; color: #fff; }
.pad-hat { background: #ca8a04; color: #000; }
.pad-bass { background: #7c3aed; color: #fff; }

.channel-params {
  display: flex;
  flex-direction: column;
}

.param-name {
  font-size: 12px;
  font-weight: 700;
  color: #f4f4f5;
}

.param-hz {
  font-size: 10px;
  color: #71717a;
}

.steps-container {
  flex: 1;
  display: grid;
  grid-template-columns: repeat(16, 1fr);
  gap: 6px;
}

.step-btn {
  aspect-ratio: 1;
  background: #27272a;
  border: 1px solid #3f3f46;
  border-radius: 4px;
  cursor: pointer;
  transition: all 0.1s ease;
}

.step-btn:hover {
  border-color: #71717a;
}

/* Group beats in sets of 4 */
.step-btn:nth-child(4n+1) {
  border-left: 2px solid #52525b;
}

.step-btn.on {
  background: #f97316;
  border-color: #fdba74;
  box-shadow: 0 0 8px rgba(249, 115, 22, 0.4);
}

.step-btn.cursor {
  outline: 2px solid #ffffff;
  outline-offset: -1px;
}

/* FX Strip */
.fx-strip {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
  margin-top: 10px;
  padding-top: 18px;
  border-top: 1px solid #27272a;
}

@media (max-width: 768px) {
  .fx-strip { grid-template-columns: 1fr; }
}

.fx-card {
  background: #121214;
  border: 1px solid #27272a;
  border-radius: 8px;
  padding: 16px;
}

.fx-title {
  font-size: 11px;
  font-weight: 700;
  color: #a1a1aa;
  letter-spacing: 0.05em;
  margin-bottom: 12px;
}

.fx-controls {
  display: flex;
  gap: 24px;
}

.dial-wrapper {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.dial-wrapper label {
  font-size: 10px;
  color: #71717a;
}

.dial-val {
  font-size: 12px;
  color: #f97316;
}

.meter-bar-container {
  display: flex;
  align-items: flex-end;
  gap: 12px;
  height: 60px;
}

.vu-meter {
  width: 20px;
  height: 50px;
  background: #18181b;
  border: 1px solid #27272a;
  border-radius: 3px;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
  overflow: hidden;
}

.vu-bar {
  width: 100%;
  background: linear-gradient(0deg, #10b981 60%, #f59e0b 85%, #ef4444 100%);
  transition: height 0.05s ease;
}

.meter-labels {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  height: 50px;
  font-size: 9px;
  color: #71717a;
}
`;

const javascript = `
(function() {
  // Web Audio Context setup
  let audioCtx = null;
  function getAudioContext() {
    if (!audioCtx) {
      const AudioContextClass = window.AudioContext || window.webkitAudioContext;
      audioCtx = new AudioContextClass();
    }
    if (audioCtx.state === 'suspended') {
      audioCtx.resume();
    }
    return audioCtx;
  }

  // Master Filter
  let filterCutoff = 3500;
  let filterReso = 4;

  // Sound Synthesizers (no external samples)
  function playKick() {
    const ctx = getAudioContext();
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();

    osc.frequency.setValueAtTime(150, ctx.currentTime);
    osc.frequency.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.5);

    gain.gain.setValueAtTime(1, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.5);

    osc.connect(gain);
    gain.connect(ctx.destination);

    osc.start(ctx.currentTime);
    osc.stop(ctx.currentTime + 0.5);
    triggerVu();
  }

  function playSnare() {
    const ctx = getAudioContext();
    // Noise buffer
    const bufferSize = ctx.sampleRate * 0.2;
    const buffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < bufferSize; i++) {
      data[i] = Math.random() * 2 - 1;
    }

    const noise = ctx.createBufferSource();
    noise.buffer = buffer;

    const noiseFilter = ctx.createBiquadFilter();
    noiseFilter.type = 'highpass';
    noiseFilter.frequency.value = 1000;

    const noiseGain = ctx.createGain();
    noiseGain.gain.setValueAtTime(1, ctx.currentTime);
    noiseGain.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.2);

    noise.connect(noiseFilter);
    noiseFilter.connect(noiseGain);
    noiseGain.connect(ctx.destination);

    // Body tone
    const osc = ctx.createOscillator();
    const oscGain = ctx.createGain();
    osc.type = 'triangle';
    osc.frequency.setValueAtTime(180, ctx.currentTime);
    oscGain.gain.setValueAtTime(0.7, ctx.currentTime);
    oscGain.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.1);

    osc.connect(oscGain);
    oscGain.connect(ctx.destination);

    noise.start(ctx.currentTime);
    osc.start(ctx.currentTime);
    osc.stop(ctx.currentTime + 0.2);
    triggerVu();
  }

  function playHat() {
    const ctx = getAudioContext();
    const bufferSize = ctx.sampleRate * 0.05;
    const buffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < bufferSize; i++) {
      data[i] = Math.random() * 2 - 1;
    }

    const source = ctx.createBufferSource();
    source.buffer = buffer;

    const filter = ctx.createBiquadFilter();
    filter.type = 'highpass';
    filter.frequency.value = 7000;

    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0.6, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.05);

    source.connect(filter);
    filter.connect(gain);
    gain.connect(ctx.destination);

    source.start(ctx.currentTime);
    triggerVu();
  }

  function playBass(noteFreq) {
    const ctx = getAudioContext();
    const osc = ctx.createOscillator();
    const filter = ctx.createBiquadFilter();
    const gain = ctx.createGain();

    osc.type = 'sawtooth';
    osc.frequency.setValueAtTime(noteFreq || 65, ctx.currentTime);

    filter.type = 'lowpass';
    filter.frequency.setValueAtTime(filterCutoff, ctx.currentTime);
    filter.frequency.exponentialRampToValueAtTime(200, ctx.currentTime + 0.3);
    filter.Q.value = filterReso;

    gain.gain.setValueAtTime(0.7, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.35);

    osc.connect(filter);
    filter.connect(gain);
    gain.connect(ctx.destination);

    osc.start(ctx.currentTime);
    osc.stop(ctx.currentTime + 0.35);
    triggerVu();
  }

  function triggerVu() {
    const l = document.getElementById('vuLeft');
    const r = document.getElementById('vuRight');
    if (!l || !r) return;
    const p = Math.floor(Math.random() * 50) + 45;
    l.style.height = p + '%';
    r.style.height = (p - 5) + '%';
    setTimeout(() => {
      l.style.height = '8%';
      r.style.height = '8%';
    }, 120);
  }

  // 16-step grid state: 4 channels x 16 steps
  const grid = [
    new Array(16).fill(false), // Kick
    new Array(16).fill(false), // Snare
    new Array(16).fill(false), // Hat
    new Array(16).fill(false)  // Bass
  ];

  // Presets
  const presets = {
    house: [
      [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
      [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
      [true, false, false, true, false, true, false, false, true, false, false, true, false, true, false, false]
    ],
    trap: [
      [true, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false],
      [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
      [true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false]
    ],
    electro: [
      [true, false, false, true, false, false, true, false, false, true, false, false, true, false, false, false],
      [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false],
      [true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false],
      [true, false, true, false, false, false, true, false, true, false, true, false, false, false, true, false]
    ]
  };

  function loadPreset(name) {
    const p = presets[name];
    if (!p) return;
    for (let c = 0; c < 4; c++) {
      for (let s = 0; s < 16; s++) {
        grid[c][s] = p[c][s];
      }
    }
    renderGridButtons();
  }

  // Generate Step LEDs
  const rulerLeds = document.getElementById('rulerLeds');
  if (rulerLeds) {
    for (let i = 0; i < 16; i++) {
      const led = document.createElement('div');
      led.className = 'step-led';
      led.id = 'led-' + i;
      rulerLeds.appendChild(led);
    }
  }

  // Generate 16 Step buttons per channel
  const channelIds = ['steps-kick', 'steps-snare', 'steps-hat', 'steps-bass'];
  channelIds.forEach((id, chIndex) => {
    const container = document.getElementById(id);
    if (!container) return;
    for (let s = 0; s < 16; s++) {
      const btn = document.createElement('button');
      btn.className = 'step-btn';
      btn.dataset.ch = chIndex;
      btn.dataset.step = s;
      btn.addEventListener('click', () => {
        grid[chIndex][s] = !grid[chIndex][s];
        btn.classList.toggle('on', grid[chIndex][s]);
        if (grid[chIndex][s]) {
          getAudioContext();
          if (chIndex === 0) playKick();
          else if (chIndex === 1) playSnare();
          else if (chIndex === 2) playHat();
          else if (chIndex === 3) playBass(65);
        }
      });
      container.appendChild(btn);
    }
  });

  function renderGridButtons() {
    channelIds.forEach((id, chIndex) => {
      const container = document.getElementById(id);
      if (!container) return;
      const btns = container.querySelectorAll('.step-btn');
      btns.forEach((btn, s) => {
        btn.classList.toggle('on', grid[chIndex][s]);
      });
    });
  }

  // Initial load
  loadPreset('house');

  // Trigger pads
  document.querySelectorAll('.trigger-pad').forEach(pad => {
    pad.addEventListener('click', function() {
      const sound = this.getAttribute('data-sound');
      getAudioContext();
      if (sound === 'kick') playKick();
      else if (sound === 'snare') playSnare();
      else if (sound === 'hat') playHat();
      else if (sound === 'bass') playBass(65);
    });
  });

  // Transport Sequencer
  let isPlaying = false;
  let currentStep = 0;
  let timerId = null;
  let bpm = 128;

  function stepTimer() {
    // Turn off previous LED & button cursors
    const prev = (currentStep + 15) % 16;
    const prevLed = document.getElementById('led-' + prev);
    if (prevLed) prevLed.classList.remove('active');
    document.querySelectorAll('.step-btn.cursor').forEach(b => b.classList.remove('cursor'));

    // Light current LED
    const curLed = document.getElementById('led-' + currentStep);
    if (curLed) curLed.classList.add('active');

    // Highlight current column
    channelIds.forEach((id) => {
      const container = document.getElementById(id);
      if (!container) return;
      const btn = container.querySelectorAll('.step-btn')[currentStep];
      if (btn) btn.classList.add('cursor');
    });

    // Play sounds
    if (grid[0][currentStep]) playKick();
    if (grid[1][currentStep]) playSnare();
    if (grid[2][currentStep]) playHat();
    if (grid[3][currentStep]) {
      const bassNotes = [55, 65, 73, 82, 55, 65, 73, 98];
      playBass(bassNotes[currentStep % bassNotes.length]);
    }

    currentStep = (currentStep + 1) % 16;
    const stepDurationMs = (60 / bpm / 4) * 1000;
    timerId = setTimeout(stepTimer, stepDurationMs);
  }

  const playBtn = document.getElementById('playToggleBtn');
  const playText = document.getElementById('playText');

  if (playBtn) {
    playBtn.addEventListener('click', () => {
      getAudioContext();
      if (isPlaying) {
        clearTimeout(timerId);
        isPlaying = false;
        playBtn.classList.remove('playing');
        playText.textContent = 'PLAY';
        document.querySelectorAll('.step-led.active').forEach(l => l.classList.remove('active'));
        document.querySelectorAll('.step-btn.cursor').forEach(b => b.classList.remove('cursor'));
      } else {
        isPlaying = true;
        currentStep = 0;
        playBtn.classList.add('playing');
        playText.textContent = 'STOP';
        stepTimer();
      }
    });
  }

  // Clear button
  const clearBtn = document.getElementById('clearPatternBtn');
  if (clearBtn) {
    clearBtn.addEventListener('click', () => {
      for (let c = 0; c < 4; c++) {
        for (let s = 0; s < 16; s++) {
          grid[c][s] = false;
        }
      }
      renderGridButtons();
    });
  }

  // BPM slider
  const bpmSlider = document.getElementById('bpmSlider');
  const bpmVal = document.getElementById('bpmVal');
  if (bpmSlider && bpmVal) {
    bpmSlider.addEventListener('input', () => {
      bpm = parseInt(bpmSlider.value, 10);
      bpmVal.textContent = bpm;
    });
  }

  // Presets
  document.querySelectorAll('.preset-btn').forEach(btn => {
    btn.addEventListener('click', function() {
      document.querySelectorAll('.preset-btn').forEach(b => b.classList.remove('active'));
      this.classList.add('active');
      loadPreset(this.getAttribute('data-preset'));
    });
  });

  // Filter dials
  const cutoffSlider = document.getElementById('filterCutoff');
  const cutoffVal = document.getElementById('cutoffVal');
  if (cutoffSlider && cutoffVal) {
    cutoffSlider.addEventListener('input', () => {
      filterCutoff = parseInt(cutoffSlider.value, 10);
      cutoffVal.textContent = filterCutoff + ' Hz';
    });
  }

  const resoSlider = document.getElementById('filterReso');
  const resoVal = document.getElementById('resoVal');
  if (resoSlider && resoVal) {
    resoSlider.addEventListener('input', () => {
      filterReso = parseFloat(resoSlider.value);
      resoVal.textContent = filterReso.toFixed(1);
    });
  }
})();
`;

export default { html, css, javascript };
