/**
 * Vercel Serverless Function — POST /api/vision-to-code
 *
 * Screenshot → Code. Takes one UI screenshot as inline image data and returns
 * framework-appropriate code generated by Gemini's vision models.
 *
 * Why this lives in its own file rather than as a `feature` on /api/ai:
 * /api/ai speaks an OpenAI-compatible chat-completions protocol to providers
 * that take text only. Vision needs a different SDK (@google/generative-ai), a
 * different message shape (inlineData parts), and a much smaller accepted body
 * — an image payload is ~1.4x the image size once base64-encoded, so it cannot
 * share the 180 KB text budget that /api/ai enforces.
 *
 * Response is always JSON: { code, framework, model } or { error }.
 */

'use strict';

const { GoogleGenerativeAI } = require('@google/generative-ai');

try {
  require('dotenv').config();
  require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
} catch (_) {}

// ─── Limits ───────────────────────────────────────────────────────────────────

/** Gemini inline data is capped well above this; 5 MB keeps the request honest. */
const MAX_IMAGE_BYTES = 5 * 1024 * 1024;

/**
 * A generous ceiling for the *request body*, which carries the base64 image
 * plus the prompt. Base64 inflates bytes by 4/3 and JSON escaping adds a little
 * more, so this sits above MAX_IMAGE_BYTES with room to spare. It also stops
 * the function from buffering an unbounded payload before validation runs.
 */
const MAX_BODY_BYTES = 8 * 1024 * 1024;

const ALLOWED_MIME_TYPES = new Set(['image/png', 'image/jpeg', 'image/webp']);

const VALID_FRAMEWORKS = new Set(['html-tailwind', 'react-tailwind', 'html-vanilla']);

// flash by default (faster, cheaper); pro is opt-in for dense or ambiguous layouts.
const DEFAULT_MODEL = 'gemini-1.5-flash';
const PRO_MODEL = 'gemini-1.5-pro';

// ─── Rate limiting (simple in-memory tracker, mirrors api/ai.js) ───────────────

const rateLimitMap = new Map();
const RATE_WINDOW_MS = 60_000;
// Lower than /api/ai's 30: a vision call costs far more than a text call.
const RATE_MAX = 10;

function checkRateLimit(ip) {
  const now = Date.now();
  const entry = rateLimitMap.get(ip);
  if (!entry || now - entry.start > RATE_WINDOW_MS) {
    rateLimitMap.set(ip, { start: now, count: 1 });
    return true;
  }
  entry.count++;
  return entry.count <= RATE_MAX;
}

// ─── Prompts ──────────────────────────────────────────────────────────────────
// One prompt per framework. They share a task description but differ in the
// output envelope, because each target consumes code differently: the plain
// editor injects html/css/js into a live page, React needs a single component,
// and vanilla CSS must live in a stylesheet rather than utility classes.

const SHARED_TASK_RULES = `
HOW TO READ THE SCREENSHOT:
- Reproduce what is visibly there: the same regions, the same relative proportions, the same content.
- Infer structure from visual hierarchy — nav bars, sidebars, cards, tables, modals, tabs, empty states.
- Derive the palette from what you actually see, and express it as concrete Tailwind classes. Never invent a generic blue/gray theme when the screenshot is clearly warm, dark, or monochrome.
- Match typography to the screenshot's character: a bold condensed heading is not a soft serif heading. Use Tailwind's font-size, font-weight and tracking utilities to convey it.
- Reproduce spacing as a consistent scale. Rounded corners, borders, and shadows should look like the original, not like defaults.
- Use realistic mock data (names, prices, dates, counts) that fits the design. Do not leave Lorem ipsum.
- Icons: use inline SVG only. Never reference an icon CDN or a package import.
- No image URLs that may not exist — use CSS gradients, shapes, or inline SVG for imagery.
- Responsive by default: stack the layout on small screens the way the design implies it should.
- No TODO comments, no placeholder stubs, no "rest of implementation here".

OUTPUT RULES:
- Output ONLY code inside a single markdown fence. No preamble, no explanation, no closing remarks, no notes after the code.
- Emit the whole component/page, not a fragment, so the code is directly runnable.
- No import or export statements in the HTML variants — they are injected into a live page.`;

const FRAMEWORK_PROMPTS = {
  'html-tailwind': `You are an expert Frontend Architect. Convert the provided UI screenshot into pixel-perfect, modern, responsive code.

TARGET: a single HTML document that uses Tailwind CSS via the Play CDN, plus one vanilla JS block.

- Return exactly one \`\`\`html fence.
- Start with \`<div class="min-h-screen">\` and a Tailwind config script block that registers any custom colour, font, or spacing tokens you rely on, e.g.
  \`<script src="https://cdn.tailwindcss.com"></script>\` followed by \`<script>tailwind.config = { theme: { extend: { ... } } }</script>\`.
- Wrap the markup in \`<body>\` only if you need it — prefer a top-level \`<div>\` so the snippet can be injected.
- Put behaviour in one trailing \`<script>\` block at the end. No \`import\`/\`export\`, no modules.
- Use arbitrary values (\`w-[137px]\`) when the screenshot needs a non-scale measurement; prefer the scale everywhere else.
${SHARED_TASK_RULES}`,

  'react-tailwind': `You are an expert Frontend Architect. Convert the provided UI screenshot into pixel-perfect, modern, responsive code.

TARGET: ONE self-contained React function component using Tailwind CSS.

- Return exactly one \`\`\`jsx fence.
- A single \`export default function App() { ... }\`. Hooks are allowed (useState for tabs, menus, modals, accordions). No custom hooks.
- No \`import\` statements at all. No component libraries — Lucide-style icons must be inline SVG, and any other dependency must be inlined as a plain object or constant inside the component body.
- Use JSX className, not class. No separate CSS file, no CSS-in-JS.
- Hold mock data in a \`const\` inside the component body (or a module-scope const above it) — never fetch it.
- Map over arrays to render repeated rows; do not hand-write ten near-identical blocks.
${SHARED_TASK_RULES}`,

  'html-vanilla': `You are an expert Frontend Architect. Convert the provided UI screenshot into pixel-perfect, modern, responsive code.

TARGET: a single self-contained HTML document with hand-written CSS. No framework, no utility classes, no CDN.

- Return exactly one \`\`\`html fence.
- Full document: \`<!DOCTYPE html>\`, \`<head>\`, inline \`<style>\`, \`<body>\`, and one \`<script>\` at the end for behaviour.
- Real CSS: custom properties for the palette, flexbox or grid for layout, a clear spacing scale, media queries for breakpoints. Class-based selectors only — never a long list of element selectors.
- No \`@import\`, no web fonts, no external CSS. System font stacks only.
- Accessible by default: semantic elements, \`aria-*\` on custom controls, visible \`:focus-visible\` states, real \`<button>\`/\`<a>\` elements.
${SHARED_TASK_RULES}`,
};

/** Optional user instruction, appended verbatim as a refinement pass. */
function buildUserMessage(framework, userPrompt) {
  const instruction = String(userPrompt || '').trim();
  const base = `TASK: Convert the attached screenshot into ${framework} code, matching its layout, typography, colors, and content as closely as possible.`;

  if (!instruction) return base;

  return [
    base,
    '',
    '=== ADDITIONAL INSTRUCTIONS FROM THE USER ===',
    instruction,
    '=== END ADDITIONAL INSTRUCTIONS ===',
    '',
    'Follow these instructions on top of the screenshot. They refine the conversion — they do not replace it.',
  ].join('\n');
}

// ─── Output cleaning ──────────────────────────────────────────────────────────

/**
 * Extracts the code from a fenced block, tolerating the model wrapping the
 * whole answer in one fence or in several. Falls back to the raw text when
 * there is no fence at all.
 */
function extractCode(rawText) {
  const trimmed = String(rawText || '').trim();
  if (!trimmed) return '';

  // Prefer the first fence that has content.
  const fenced = trimmed.match(/```(?:[a-zA-Z0-9+#-]*)\s*\n?([\s\S]*?)```/);
  if (fenced) return fenced[1].trim();

  return trimmed;
}

// ─── Handler ──────────────────────────────────────────────────────────────────

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const ip = req.headers['x-forwarded-for'] || req.socket?.remoteAddress || 'unknown';
  if (!checkRateLimit(ip)) {
    return res.status(429).json({ error: 'Too many screenshot requests — please wait a moment.' });
  }

  const body = req.body || {};

  // ── Validation ──
  if (typeof body.imageBase64 !== 'string' || !body.imageBase64.trim()) {
    return res.status(400).json({ error: 'An image is required.' });
  }

  const mimeType = String(body.mimeType || '').trim().toLowerCase();
  if (!ALLOWED_MIME_TYPES.has(mimeType)) {
    return res.status(400).json({
      error: `Unsupported image type "${mimeType}". Use PNG, JPEG, or WebP.`,
    });
  }

  const framework = String(body.framework || 'html-tailwind').trim();
  if (!VALID_FRAMEWORKS.has(framework)) {
    return res.status(400).json({
      error: `Unsupported framework "${framework}". Must be one of: ${[...VALID_FRAMEWORKS].join(', ')}`,
    });
  }

  // Base64 inflates bytes by 4/3, so the encoded length is checked against an
  // inflated threshold rather than decoded first — decoding a hostile payload
  // just to reject it is wasted work.
  const imageBase64 = body.imageBase64.trim().replace(/\s+/g, '');
  const approxBytes = Math.floor((imageBase64.length * 3) / 4);
  if (approxBytes > MAX_IMAGE_BYTES) {
    return res.status(413).json({ error: 'Image is larger than 5 MB — please use a smaller screenshot.' });
  }
  if (approxBytes > MAX_BODY_BYTES) {
    return res.status(413).json({ error: 'Payload too large — please use a smaller screenshot.' });
  }

  // ── Model ──
  const requestedModel = String(body.model || '').trim();
  const model = [DEFAULT_MODEL, PRO_MODEL].includes(requestedModel) ? requestedModel : DEFAULT_MODEL;

  // A key may arrive in the body (user-supplied, per the other AI features) or
  // from the environment. Body wins so a user can override a stale deploy-time key.
  const apiKey = String(body.apiKey || '').trim() || String(process.env.GEMINI_API_KEY || '').trim();
  if (!apiKey) {
    return res.status(500).json({
      error: 'Vision-to-Code is not configured — GEMINI_API_KEY is missing.',
    });
  }

  try {
    const genAI = new GoogleGenerativeAI(apiKey);
    const generativeModel = genAI.getGenerativeModel({
      model,
      systemInstruction: {
        role: 'system',
        parts: [{ text: FRAMEWORK_PROMPTS[framework] }],
      },
      generationConfig: {
        temperature: 0.35,
        maxOutputTokens: 16384,
      },
    });

    const result = await generativeModel.generateContent([
      { text: buildUserMessage(framework, body.userPrompt) },
      {
        inlineData: {
          mimeType,
          data: imageBase64,
        },
      },
    ]);

    const rawText = result?.response?.text?.();
    const code = extractCode(rawText);

    if (!code) {
      return res.status(502).json({ error: 'Gemini returned no code for that screenshot.' });
    }

    return res.json({ code, framework, model });
  } catch (err) {
    const message = err?.message || 'Unknown error';

    // Surface quota and auth problems as actionable messages rather than a
    // generic failure — those are the two the user can actually fix.
    if (/API key not valid|API_KEY_INVALID|PERMISSION_DENIED/i.test(message)) {
      return res.status(502).json({ error: 'Gemini rejected the API key — check GEMINI_API_KEY.' });
    }
    if (/RESOURCE_EXHAUSTED|quota|rate limit/i.test(message)) {
      return res.status(429).json({ error: 'Gemini rate limit reached — please try again shortly.' });
    }
    if (/SAFETY|blocked/i.test(message)) {
      return res.status(422).json({ error: 'Gemini declined to process that image.' });
    }
    if (/timeout|ETIMEDOUT|ECONNABORTED/i.test(message)) {
      return res.status(504).json({ error: 'Vision request timed out — please try again.' });
    }

    return res.status(502).json({ error: `Vision generation failed: ${message.slice(0, 200)}` });
  }
};

// Exported for testing / reuse.
module.exports.FRAMEWORK_PROMPTS = FRAMEWORK_PROMPTS;
module.exports.extractCode = extractCode;
module.exports.buildUserMessage = buildUserMessage;